config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gallery.urls')),
]

# urlpatterns += i18n_patterns(
#     url(r'^admin/', include(admin.site.urls)),
# )


from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
from django.urls import path
from . import views as gallery_view
from account import views as account_view
from cart import views as cart_view

app_name = 'gallery'

urlpatterns = [
    
    path('', gallery_view.CategoryList.as_view(), name='index'),
    path('about', gallery_view.about, name='about'),
    path('rahnama', gallery_view.rahnama, name='rahnama'),
    path('offer', gallery_view.OfferList.as_view(), name='offer'),
    path('books/<slug:cat_slug>', gallery_view.BookList.as_view(), name='books'),
    path('books/<slug:cat_slug>/<str:filter>', gallery_view.FilterResultsView.as_view(), name='books_filter'),
    path('search', gallery_view.SearchResultsView.as_view(), name='search_results'),

    path('login', account_view.Login.as_view(), name='login'),
    path('logout', account_view.Logout.as_view(), name='logout'),
    path('register', account_view.Register.as_view(), name='register'),

    path('api/<int:pk>/like_or_dislike', gallery_view.like_or_dislike, name='like_or_dislike'),
    path('api/<int:pk>/comment', gallery_view.comment, name='comment'),
    path('api/<int:pk>/star/<int:score>', gallery_view.star, name='star'),

    path('book/<slug:slug>', gallery_view.BookDetail.as_view(), name='detail'),

    path('shoppingcart', cart_view.OrderSummaryView.as_view(), name='shoppingcart'),
    path('cart/add/<int:id>/', cart_view.add_to_cart, name='cart_add'),
    
    path('cart/item_clear/<int:id>/', cart_view.remove_from_cart, name='item_clear'),

    path('cart/item_increment/<int:id>/', cart_view.add_to_cart, name='item_increment'),
    path('cart/item_decrement/<int:id>/', cart_view.remove_single_item_from_cart, name='item_decrement'),
    path('cart/cart-detail/', cart_view.OrderSummaryView.as_view(), name='cart_detail'),

    path('cart/history/', cart_view.OrderedCartList.as_view(), name='history'),


    path('request/', gallery_view.send_request, name='request'),
    path('verify/', gallery_view.verify, name='verify'),
]

gallery/models.py
from django.db import models
from account.models import User
from uuslug import uuslug as slugify
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان دسته‌بندی')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته‌بندی')
    photo = models.ImageField(upload_to="cat_images", verbose_name='تصویر دسته‌بندی')
    class Meta:
        verbose_name = 'دسته‌بندی'
        verbose_name_plural = 'دسته‌بندی ها'
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, instance=self)
        super(Category, self).save(*args, **kwargs)
    def __str__(self):
        return '{}'.format(self.title)


class Book(models.Model):
    name = models.CharField(max_length=200, verbose_name='عنوان کتاب')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='آدرس کتاب')
    description = models.TextField(verbose_name="توضیحات")
    image = models.ImageField(upload_to="images", verbose_name='تصویر کتاب')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تشکیل کتاب')
    author = models.CharField(max_length=200, verbose_name='نویسنده')
    number_of_pages = models.IntegerField(verbose_name='تعداد صفحات کتاب')
    price = models.IntegerField(verbose_name='قیمت')
    percent = models.IntegerField(verbose_name='درصد تخفیف')
    category = models.ManyToManyField(Category, verbose_name='دسته‌بندی')
    offer = models.BooleanField(default=False, verbose_name='پیشنهاد ویژه')

    @property
    def get_book_offer_price(self):
        new_price = self.price * (1 - (self.percent / 100))
        return int(new_price)

    @property
    def get_avg_stars_percent(self):
        book_stars = Star.objects.filter(book=self)
        book_stars_scores = [bs.score for bs in book_stars]
        if len(book_stars) == 0:
            avg = 0
        else:
            avg = sum(book_stars_scores) / len(book_stars)
        return int((avg/5)*100)

    class Meta:
        verbose_name = 'کتاب'
        verbose_name_plural = 'کتابها'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, instance=self)
        super(Book, self).save(*args, **kwargs)
        
    def __str__(self):
        return '{} - {}'.format(self.name, self.author)


class Comment(models.Model):
    content = models.TextField(verbose_name='محتوا')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='comments', verbose_name='کتاب')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')

    likes = models.ManyToManyField(User, blank=True, related_name='likes', verbose_name='لایک ها')

    def __str__(self):
        return '{} - {}'.format(self.book.name, self.user.username)
    
    class Meta:
        verbose_name = 'دیدگاه'
        verbose_name_plural = 'دیدگاه ها'
        ordering = ['-created_date']


class Star(models.Model):
    score = models.IntegerField(default=0, verbose_name='امتیاز',
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0),
        ]
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='stars', verbose_name='کتاب')
    class Meta:
        verbose_name = 'امتیاز ستاره‌ای'
        verbose_name_plural = 'امتیازهای ستاره‌ای'
    def __str__(self):
        return '{} - {} - {}'.format(self.score, self.book.name, self.user.username)

gallery/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import get_object_or_404, redirect
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from zeep import Client
from .models import Book, Comment, Star, Category
from cart.models import Order

from django.shortcuts import render
# from django.views.generic import ListView
from django.db.models import Q

# Create your views here.


class SearchResultsView(ListView):
    model = Book
    template_name = 'gallery/search.html'
    context_object_name = 'products'

    def get_queryset(self):
        query = self.request.GET.get('search')
        products=Book.objects.filter(Q(name__icontains=query)|Q(author__icontains=query)|Q(description__icontains=query))
        return products
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search"] = self.request.GET.get('search')
        return context
    ordering = ['-created']
    paginate_by = 12


class FilterResultsView(ListView):
    model = Book
    template_name = 'gallery/book_list_filter.html'

    def get_queryset(self):
        global cat
        global filter_name
        slug = self.kwargs.get('cat_slug')
        filter_name = self.kwargs.get('filter')
        cat = get_object_or_404(Category, slug=slug)

        if filter_name == 'newest':
            cat_filter_books = Book.objects.filter(category=cat).order_by('-created')
        elif filter_name == 'cheapest':
            cat_filter_books = sorted(Book.objects.filter(category=cat), key=lambda a: a.get_book_offer_price)
        elif filter_name == 'starest':
            cat_filter_books = sorted(Book.objects.filter(category=cat), key=lambda a: a.get_avg_stars_percent, reverse=True)
        return cat_filter_books

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = cat
        context["filter"] = filter_name
        return context
    
    paginate_by = 12


# def items(request):
#     items = Book.objects.all()
#     return items


def about(request):
    return render(request, 'gallery/about.html')

def rahnama(request):
    return render(request, 'gallery/rahnama.html')

class CategoryList(ListView):
    model = Category
    template_name = 'gallery/index.html'


# class AboutList(ListView):
#     model = Category
#     template_name = 'gallery/about.html'


# class RahnamaList(ListView):
#     model = Category
#     template_name = 'gallery/rahnama.html'

# class ShoppingCart(ListView):
#     model = Book
#     template_name = 'gallery/shoppingcart.html'


class OfferList(ListView):
    model = Book
    template_name = 'gallery/offer.html'
    def get_queryset(self):
        offer_books = Book.objects.filter(Q(offer=True)|Q(percent__gt=0))
        return offer_books
    paginate_by = 12
    ordering = ['-created']


class BookList(ListView):
    model = Book

    def get_queryset(self):
        global cat
        slug = self.kwargs.get('cat_slug')
        cat = get_object_or_404(Category, slug=slug)
        cat_books = Book.objects.filter(category=cat)
        return cat_books

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = cat
        return context

    paginate_by = 12
    ordering = ['-created']


class BookDetail(DetailView):

    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Book, slug=slug)


# @login_required
def like_or_dislike(request, pk):
    # print(request.resolver_match)
    user = request.user
    comment = get_object_or_404(Comment, pk=pk)
    comment_likes_users = comment.likes.all()
    count = comment_likes_users.count()

    if user.is_anonymous:
        return JsonResponse({
            'likes': count,
            'status': 'not_login',
        })

    if user in comment_likes_users:
        comment.likes.remove(user)
        count -= 1
        user_in_likes = False
    else:
        comment.likes.add(user)
        count += 1
        user_in_likes = True

    return JsonResponse({
        'status': user.is_authenticated,
        'likes': count,
        'user_in_likes': user_in_likes,
    })


def comment(request, pk):
    # print(request.resolver_match)
    user = request.user
    book = get_object_or_404(Book, pk=pk)

    # print(request)

    if user.is_anonymous:
        return JsonResponse({
            'status': 'not_login',
        })
    content = request.POST.get('content')
    if content == '':
        return JsonResponse({
            'status': 'bad_content',
        })
    Comment.objects.create(
        user=user,
        book=book,
        content=content
    )
    book_comments = book.comments.all()
    count = book_comments.count()

    all_comments = []
    for cmmnt in book_comments:
        likers = cmmnt.likes.all()
        like_count = likers.count()
        user_in_likes = user in likers
        all_comments.append({'created': cmmnt.created_date, 'username': cmmnt.user.username, 'content': cmmnt.content,
                             'like_count': like_count, 'user_in_likes': user_in_likes, 'pk': cmmnt.pk})

    return JsonResponse({
        'status': user.is_authenticated,
        'count': count,
        'user': user.username,
        'book_comments': all_comments
    })


def star(request, pk, score):
    # print(request.resolver_match)
    user = request.user
    book = get_object_or_404(Book, pk=pk)

    book_stars = Star.objects.filter(book=book)
    book_stars_users = [bs.user for bs in book_stars]
    book_stars_scores = [bs.score for bs in book_stars]

    if len(book_stars) == 0:
        avg = 0
    else:
        avg = sum(book_stars_scores) / len(book_stars)
    avg = int((avg / 5) * 100)

    if user.is_anonymous:
        return JsonResponse({
            'avg': avg,
            'status': 'not_login',
        })
    if score not in [0, 1, 2, 3, 4, 5]:
        return JsonResponse({
            'avg': avg,
            'status': 'bad_content',
        })

    user_in_stars = True
    if user in book_stars_users:
        user_index = book_stars_users.index(user)
        book_stars_scores[user_index] = score
        Star.objects.filter(user=user, book=book).update(score=score)
    else:
        Star.objects.create(
            user=user,
            book=book,
            score=score
        )
        book_stars_users.append(user)
        book_stars_scores.append(score)

    avg = sum(book_stars_scores) / len(book_stars_users)
    avg = int((avg / 5) * 100)
    return JsonResponse({
        'status': user.is_authenticated,
        'avg': avg,
        'user_in_stars': user_in_stars,
        'user_score': score
    })


###zarinpal###

MERCHANT = 'aaaaasssdfghjkliuytrfghhbhnhgfdsdedf'
client = Client('https://sandbox.zarinpal.com/pg/services/WebGate/wsdl')
#amount = 1000  # Toman / Required

description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required
email = 'email@example.com'  # Optional
mobile = '09123456789'  # Optional
CallbackURL = 'http://localhost:8000/verify/' # Important: need to edit for realy server.

@login_required
def send_request(request):
    cart_id = int(request.POST.get('cart_id'))
    order = get_object_or_404(Order, pk=cart_id)
    amount = order.get_total()
    email = request.user.email
    result = client.service.PaymentRequest(MERCHANT, amount, description, email, mobile, '{}?cartid={}'.format(CallbackURL, cart_id))
    if result.Status == 100:
        return redirect('https://sandbox.zarinpal.com/pg/StartPay/' + str(result.Authority))
    else:
        return HttpResponse('Error code: ' + str(result.Status))

@login_required
def verify(request):
    print(request.GET)
    cart_id = int(request.GET.get('cartid'))
    order = get_object_or_404(Order, pk=cart_id)
    amount = order.get_total()
    if request.GET.get('Status') == 'OK':
        result = client.service.PaymentVerification(MERCHANT, request.GET['Authority'], amount)
        if result.Status == 100:
            order.ordered = True
            order.ordered_price = amount
            order.save()
            return render(request, 'gallery/verify.html', context={'result': str(result.RefID), 'status': True})
        elif result.Status == 101:
            return render(request, 'gallery/verify.html', context={'result': str(result.Status), 'status': False})
        else:
            return render(request, 'gallery/verify.html', context={'result': str(result.Status), 'status': False})
    else:
        return render(request, 'gallery/verify.html')

templates/gallery/book_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{category.title}}{% endblock %}
{% block main %}


<section class="mainbody">

    <!--Filters-->



<h5 style="color:rgb(175, 12, 12);text-align: center;text-decoration:none;">:مرتب سازی براساس</h5>
<div style="text-align:center;float:center;">
    <div class="btn-group btn-group-toggle" >
        <a class="btn btn-outline-light" style="color:rgb(175, 12, 12);" href="{% url 'gallery:books_filter' category.slug 'newest' %}">جدیدترین ها</a>
        <a class="btn btn-outline-light" style="color:rgb(175, 12, 12);" href="{% url 'gallery:books_filter' category.slug 'cheapest' %}">ارزان ترین ها</a>
        <a class="btn btn-outline-light" style="color:rgb(175, 12, 12);" href="{% url 'gallery:books_filter' category.slug 'starest' %}"> محبوب ترین ها</a>
    </div>
<hr>
<br>
</div>


    <!--filters-->



<!--***********************************************************mahsoolat***********************************************************-->


<section class="mahsoolat">
  <h3 style="color:rgb(175, 12, 12);text-align: center;text-decoration:underline;">{{category.title}}</h3>
  




<br>
<div class="container">
    <div class="row">
        {% for book in object_list %}

        <div class="col-md-3 col-sm-6">
            <div class="product-grid4">
                <div class="product-image4">
                    <a href="{% url 'gallery:detail' book.slug %}">
                        <img class="pic-1" src="{{book.image.url}}">
                        <img class="pic-2" src="{{book.image.url}}">
                    </a>
                    <ul class="social">
                        <li><a href="{% url 'gallery:detail' book.slug %}" data-tip="نمایش"><i class="fa fa-eye"></i></a></li>
                        
                        <li><a href="{% url 'gallery:cart_add' book.id %}" data-tip="اضافه به سبد خرید"><i class="fa fa-shopping-cart"></i></a></li>
                    </ul>
                
                </div>
                <div class="product-content">
                  <h3 class="title"><a href="{% url 'gallery:detail' book.slug %}">کتاب {{book.name}}</a></h3>
                  <h4 class="title">نویسنده:{{book.author}}</h4>
                  <h4 class="title">
                    <div class="price">قیمت:
                        {% if not book.percent == 0 %}
                        {{ book.get_book_offer_price }}
                        <span>{{book.price}}</span>
                        {% elif book.percent == 0 %}
                        {{book.price}}
                        {% endif %}
                    </div>
                  </h4>
                    <a class="add-to-cart" href="{% url 'gallery:cart_add' book.id %}">افزودن به سبد خرید</a>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:4 %}
  </div>
</div>
<br>
<div class="container">
  <div class="row">
        {% endif %}
    {% endfor %}
    </div>
  </div>



       
   </section>  
  

    
<br>
<br>
<br>


<!--***********************************************************mahsoolat*********************************************************-->


<!--pagenation-->

<nav aria-label="Page navigation example bg-light">
    <ul class="pagination justify-content-center">
       {% if page_obj.has_previous %}
        <li class="page-item">
         
            <a class="page-link" href="{% url 'gallery:books' category.slug %}?page={{page_obj.previous_page_number}}" aria-label="Previous"   style="color:rgb(175, 12, 12);">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>

          </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
          <li class="page-item"><a class="page-link" style="color:rgb(175, 12, 12);"   href="{% url 'gallery:books' category.slug %}?page={{i}}">{{i}}</a></li>
        {% endfor %}
          
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="{% url 'gallery:books' category.slug %}?page={{page_obj.next_page_number}}" aria-label="Next"    style="color:rgb(175, 12, 12);" >
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        {% endif %}
    </ul>
  </nav>


<!--pagenation-->



{% endblock %}

templates/gallery/ordered_list.html
{% load static %}
{% comment %} {% load cart_tag %} {% endcomment %}

        <!DOCTYPE html>
        <html>
        <head>
            <title>سبد خرید</title>
            <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'js/slick/slick.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'js/slick/slick-theme.css' %}">
        </head>
        {% for message in messages %}
        <div class="container-fluid p-0">
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        </div>
        {% endfor %}

        <body style="background: rgb(204, 106, 57);">
        <a href="{% url 'gallery:index' %}" class="col-lg-12 btn btn-warning text-white"><i class="fa fa-angle-left"></i> ادامه خرید</a>
        {% for object in object_list %}
            <div class="container main-section">
            
                <div class="row">
                    
                    <div class="col-lg-12 pl-3 pt-3">
                        <table class="table table-hover bg-light">
                            <thead>
                                  <tr>
                                    <th>محصول</th>
                                    <th>قیمت</th>
                                    <th>درصد تخفیف</th>
                                    <th style="width:10%;">تعداد</th>
                                    <th>قیمت نهایی</th>
                                   
                                  </tr>
                            </thead>
                            <tbody>
                                {% for order_item in object.items.all %}
                                  <tr>
                                    <td style="width:50%">
                                        <div class="row">
                                            <div class="col-lg-2 col-md-2 mb-2 mb-md-0 Product-img">
                                                <img src="{{order_item.item.image.url}}" alt="..." class="img-responsive"/>
                                            </div>
                                            <div class="col-lg-10">
                                                <h4 class="nomargin">کتاب {{ order_item.item.name }}</h4>
                                                <p>{{ order_item.item.author }}</p>
                                            </div>
                                        </div>
                                    </td>
                                    <td> {{ order_item.item.price }} </td>
                                    <td> {{ order_item.item.percent }} </td>
                                    <td data-th="Quantity">
                                        {{ order_item.quantity }}
                                        {% comment %} <input type="number" class="form-control text-center" value="{{value.quantity}}">
                                        <a href="{% url 'gallery:item_increment' order_item.item.id %}" style="margin:8px; color: black">+</a>
                                        {% if order_item.quantity > 1 %}
                                        <a href="{% url 'gallery:item_decrement' order_item.item.id %}" style="margin:8px; color:black">-</button></a>
                                        {% endif %}
                                        <a href="{% url 'gallery:item_clear' order_item.item.id %}" style="margin:8px; color:red">حذف</button></a> {% endcomment %}
                                        
                                    </td>
                                    <td>{{ order_item.get_final_price }}</td>
                                    
                                  </tr>
                                {% endfor %}




                            </tbody>
                            <tfoot>
                                <tr>
                                    <td>{% if object.being_delivered %}
                                                <span class="badge badge-success">ارسال شده</span>
                                              {% else %}
                                                <span class="badge badge-warning">ارسال نشده</span>
                                              {% endif %}
                                    </td>
                                    <td>{% if object.received %}
                                                <span class="badge badge-success">تحویل شده</span>
                                              {% else %}
                                                <span class="badge badge-warning">تحویل نشده</span>
                                              {% endif %}
                                    </td>
                                    
                                    <td colspan="2" class="hidden-xs"><strong>قیمت کل:{{ object.ordered_price }} </strong></td>
                                    

                                    <td class="hidden-xs text-center" style="width:10%;">

                                    {% comment %} {% if object.get_total > 0 %}
                                        <form method="POST" id="cart_form" action="{% url 'gallery:request' %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="cart_id" id="cart_id" value="{{ object.pk }}">

                                            <button type="submit" class="btn btn-success btn-block">انتقال به درگاه <i class="fa fa-angle-right"></i></button></td>
                                        </form>
                                    {% endif %} {% endcomment %}
                                </tr>
                            </tfoot>
                            {% comment %} <a href="{% url 'gallery:cart_detail' %}">clear all</a> {% endcomment %}
                        </table>
                    </div>
                </div>
            </div>
        {% endfor %}
        </body>
        </html>
        

templates/gallery/shoppingcart.html
{% load static %}
{% comment %} {% load cart_tag %} {% endcomment %}

        <!DOCTYPE html>
        <html>
        <head>
            <title>سبد خرید</title>
            <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'js/slick/slick.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'js/slick/slick-theme.css' %}">
        </head>
        {% for message in messages %}
        <div class="container-fluid p-0">
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        </div>
        {% endfor %}
        <body style="background: rgb(204, 106, 57);">
            <div class="container main-section">
                <div class="row">
                    <div class="col-lg-12 pb-2">
                        <h4  style="text-align:right;">سبد خرید</h4>
                    </div>
                    <div class="col-lg-12 pl-3 pt-3">
                        <table class="table table-hover bg-light">
                            <thead>
                                  <tr>
                                    <th>محصول</th>
                                    <th>قیمت</th>
                                    <th>درصد تخفیف</th>
                                    <th style="width:10%;">تعداد</th>
                                    <th>قیمت نهایی</th>
                                   
                                  </tr>
                            </thead>
                            <tbody>
                                {% for order_item in object.items.all %}
                                  <tr>
                                    <td style="width:50%">
                                        <div class="row">
                                            <div class="col-lg-2 col-md-2 mb-2 mb-md-0 Product-img">
                                                <img src="{{order_item.item.image.url}}" alt="..." class="img-responsive"/>
                                            </div>
                                            <div class="col-lg-10">
                                                <h4 class="nomargin">کتاب {{ order_item.item.name }}</h4>
                                                <p>{{ order_item.item.author }}</p>
                                            </div>
                                        </div>
                                    </td>
                                    <td> {{ order_item.item.price }} </td>
                                    <td> {{ order_item.item.percent }} </td>
                                    <td data-th="Quantity">
                                        {% comment %} <input type="number" class="form-control text-center" value="{{value.quantity}}"> {% endcomment %}
                                        <a href="{% url 'gallery:item_increment' order_item.item.id %}" style="margin:8px; color: black">+</a>
                                        {{ order_item.quantity }}
                                        {% if order_item.quantity > 1 %}
                                        <a href="{% url 'gallery:item_decrement' order_item.item.id %}" style="margin:8px; color:black">-</button></a>
                                        {% endif %}
                                        <a href="{% url 'gallery:item_clear' order_item.item.id %}" style="margin:8px; color:red">حذف</button></a>
                                        
                                    </td>
                                    <td>{{ order_item.get_final_price }}</td>
                                    
                                  </tr>
                                {% endfor %}




                            </tbody>
                            <tfoot>
                                <tr>
                                    <td><a href="{% url 'gallery:index' %}" class="btn btn-warning text-white"><i class="fa fa-angle-left"></i> ادامه خرید</a></td>
                                    <td colspan="2" class="hidden-xs"><strong>قیمت کل:{{ object.get_total }} </strong></td>
                                    

                                    <td class="hidden-xs text-center" style="width:10%;">
                                    {% if object.get_total > 0 %}
                                        <form method="POST" id="cart_form" action="{% url 'gallery:request' %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="cart_id" id="cart_id" value="{{ object.pk }}">

                                            <button type="submit" class="btn btn-success btn-block">انتقال به درگاه <i class="fa fa-angle-right"></i></button></td>
                                        </form>
                                    {% endif %}
                                </tr>
                            </tfoot>
                            {% comment %} <a href="{% url 'gallery:cart_detail' %}">clear all</a> {% endcomment %}
                        </table>
                    </div>
                </div>
            </div>
            <script src="{% static 'js/jquery.min.js' %}"></script>
            <script src="{% static 'js/bootstrap.js' %}"></script>
        </body>
        </html>
        